#!/bin/bash

dotnet msbuild /p:Configuration=Debug /property:GenerateFullPaths=true
mono --debug ~/.nuget/packages/xunit.runner.console/2.4.1/tools/net472/xunit.console.exe bin/Debug/net472/AxTests.exe -parallel none -noshadow -verbose
