#!/bin/bash

cd $(dirname $0)

# Stage 0 Install chroot

# debootstrap stretch aximo-chroot
# sudo mount --bind /proc aximo-chroot/proc
# sudo mount --bind /sys aximo-chroot/sys
# sudo mount --bind /dev aximo-chroot/dev
# sudo mount --bind /dev/pts aximo-chroot/dev/pts

# Stage 1 Preparation (manual)

# apt-get update && apt-get -y install git sudo
# git clone --recursive https://github.com/AximoGames/AxEngine.git
# Now Call .github/workfows/install-chroot

# Stage 2
echo deb http://deb.debian.org/debian stretch-backports main >> /etc/apt/sources.list
apt-get wget zsh git-lfs

# comfort
apt-get -y install zsh
git clone --recursive https://github.com/Arakis/prezto.git ~/.zprezto
# Manual: launch zsh and run: ~/.zprezto/install

./install-dotnet-debian9

#---
apt-get install -y build-essential cmake libosmesa6-dev gdb

# build GLFW:

# git clone --recursive https://github.com/glfw/glfw.git
# cd glfw
# git checkout 3.3.2
# cmake -DGLFW_USE_OSMESA=ON -DBUILD_SHARED_LIBS=ON .
# make
# cp src/libglfw.so* ../AxEngine/Tests/bin/Debug/netcoreapp3.1

# Test:

# dotnet test Tests --no-build -v detailed