name: Tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-unix:
    name: Linux Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    #- run: dotnet build
    - name: Update Package respository
      run: sudo apt-get -y -o Acquire::Check-Valid-Until=false update
    - run: .github/workflows/setup-xvfb
    - run: .github/workflows/xvfb-daemon-run dotnet test Tests -v detailed -- RunConfiguration.TestSessionTimeout=10000
      env:
      - LIBGL_ALWAYS_SOFTWARE: true
    # - name: Running tests
    #   run: dotnet test -p Tests
    #   env:
    #     LIBGL_ALWAYS_SOFTWARE: true
    #     GALLIUM_DRIVER: softpipe