name: Tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-unix:
    name: Linux Test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - uses: actions/setup-dotnet@v1.4.0
      with:
        dotnet-version: '3.1.100' # SDK Version to use.
    #- run: dotnet build
    - name: Update Package respository
      run: sudo apt-get -y -o Acquire::Check-Valid-Until=false update
    #- run: sudo .github/workflows/setup-xvfb
    - run: |
        cd .github/workflows

        ls
        pwd

        sudo apt-get  install -y xvfb x11vnc x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps \
          libgl1-mesa-glx

        sudo cp xvfb_init /etc/init.d/xvfb
        sudo chmod a+x /etc/init.d/xvfb

        sudo cp xvfb_daemon_run /usr/bin/xvfb-daemon-run
        sudo chmod a+x /usr/bin/xvfb-daemon-run

    - run: xvfb_daemon_run dotnet test Tests
    # - name: Running tests
    #   run: dotnet test -p Tests
    #   env:
    #     LIBGL_ALWAYS_SOFTWARE: true
    #     GALLIUM_DRIVER: softpipe