#!/bin/bash

#set -e

cd $(dirname $0)

sudo apt-get  install -y xvfb x11vnc x11-xkb-utils xfonts-100dpi xfonts-75dpi xfonts-scalable xfonts-cyrillic x11-apps \
    libgl1-mesa-glx

sudo cp xvfb_init /etc/init.d/xvfb
sudo chmod a+x /etc/init.d/xvfb

sudo chmod a+x xvfb-daemon-run

export DISPLAY=:99
