#!/bin/bash

set -e
cd $(dirname $0)

export DEBIAN_FRONTEND=noninteractive

sudo sed -i s/stretch/buster/g /etc/apt/sources.list
sudo apt-get -y -o Acquire::Check-Valid-Until=false update
sudo apt-get -y dist-upgrade